# -*- coding: utf-8 -*-
"""Aula3Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18KrcTI04jO2BkCsyl11oiK_G4RiZOeNk
"""

#importando as bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('seaborn')

#upload do arquivo
from google.colab import files
arq = files. upload()

#criando nosso DataFrame
df = pd.read_excel('AdventureWorks.xlsx')

#quantidade de linha e colunas
df.shape

#verificar os tipos de dados
df.dtypes

#qual a receita total?
df['Valor Venda'].sum()

#qual o custo total?
df['custo'] = df['Custo Unitário'].mul(df['Quantidade']) #criando coluna custo

df.head()

#qual o custo total?
round(df['custo'].sum(), 2)

#agora que temos a receita e custo e o total, podemos achar o lucro total
#vamos criar um coluna de Lucro que será Receita - Custo
df['lucro'] = df['Valor Venda'] - df['custo']

df.head(1)

#total lucro
round(df['lucro'].sum(), 2)

#criando uma coluna com total de dias para enviar o produto
df['Tempo_envio'] = df['Data Envio'] - df['Data Venda']

df.head(1)

#extraindo apenas os dias
df['Tempo_envio'] = (df['Data Envio'] - df['Data Venda']).dt.days

df.head(1)

#verificando o tipo da coluna Tempo_envio
df['Tempo_envio'].dtype

#média do tempo de envio por Marca
df.groupby('Marca')['Tempo_envio'].mean()

#verificando se temos dados faltantes
df.isnull().sum()



"""# Como descobrir o Lucro por Ano e por Marca."""

#vamos agrupar por ano e marca
df.groupby([df['Data Venda'].dt.year, 'Marca'])['lucro'].sum()

pd.options.display.float_format = '{:20,.2f}'.format

#resetando o index
lucro_ano = df.groupby([df['Data Venda'].dt.year, 'Marca'])['lucro'].sum().reset_index()
lucro_ano

#qual o total de produtos vendidos?
df.groupby('Produto')['Quantidade'].sum().sort_values(ascending=False)

#gráfico total de produtos vendidos
df.groupby('Produto')['Quantidade'].sum().sort_values(ascending=True).plot.barh(title= 'Total Produtos Vendidos')

df.groupby(df['Data Venda'].dt.year)['lucro'].sum().plot.bar(title='Lucro x ANO')
plt.xlabel('Ano')
plt.ylabel('Receita');

df.groupby(df['Data Venda'].dt.year)['lucro'].sum()

#selecionando apenas as vendas de 2009
df_2009 = df[df['Data Venda'].dt.year == 2009]

df_2009.groupby('Marca')['lucro'].sum().plot.bar(title='Lucro x Marca')
plt.xlabel('Marca')
plt.ylabel('Lucro')
plt.xticks(rotation = 'horizontal');

df_2009.groupby('Classe')['lucro'].sum().plot.bar(title='Lucro x Classe')
plt.xlabel('Classe')
plt.ylabel('Lucro')
plt.xticks(rotation='horizontal');

df['Tempo_envio'].describe()

#grafico de boxplot
plt.boxplot(df['Tempo_envio']);

#histograma
plt.hist(df['Tempo_envio']);

#tempo mínimo de envio
df['Tempo_envio'].min()

#tempo máximo de envio
df['Tempo_envio'].max()

#identificando o outlier
df[df['Tempo_envio']==20]

#salvando o arquivo formato csv
df.to_csv('df_vendas_novo.csv', index=False)